-- +goose Up
-- +goose ENVSUB ON
GRANT ALL ON SCHEMA public TO $DATABASE_USER;
GRANT ALL ON ALL TABLES IN SCHEMA public TO $DATABASE_USER;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO $DATABASE_USER;
-- +goose ENVSUB OFF

-- +goose Down
-- +goose ENVSUB ON
REVOKE ALL ON SCHEMA public FROM $DATABASE_USER;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM $DATABASE_USER;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM $DATABASE_USER;
-- +goose ENVSUB OFF
