services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $DATABASE_NAME

    # volumes:
    #   - "./init.sh:/docker-entrypoint-initdb.d/init.sh"
