// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package storage

import (
	"context"
)

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, date, iso_date FROM dogdish.event
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]DogdishEvent, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DogdishEvent
	for rows.Next() {
		var i DogdishEvent
		if err := rows.Scan(&i.ID, &i.Date, &i.IsoDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
